// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrvQ0MkD4iA33JYGclWTJJ9vVE7rnCslE',
    appId: '1:881167121290:android:f12b35f250031b0435a673',
    messagingSenderId: '881167121290',
    projectId: 'smart-life-17183-d0c98',
    storageBucket: 'smart-life-17183-d0c98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrvQ0MkD4iA33JYGclWTJJ9vVE7rnCslE',
    appId: '1:881167121290:ios:f12b35f250031b0435a673',
    messagingSenderId: '881167121290',
    projectId: 'smart-life-17183-d0c98',
    storageBucket: 'smart-life-17183-d0c98.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrvQ0MkD4iA33JYGclWTJJ9vVE7rnCslE',
    appId: '1:881167121290:web:f12b35f250031b0435a673',
    messagingSenderId: '881167121290',
    projectId: 'smart-life-17183-d0c98',
    authDomain: 'smart-life-17183-d0c98.firebaseapp.com',
    storageBucket: 'smart-life-17183-d0c98.firebasestorage.app',
  );
}
